/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionKey = IDL.Text;
export const ConversationId = IDL.Nat;
export const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
export const Timestamp = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : Role,
  'timestamp' : Timestamp,
});
export const ConversationPublic = IDL.Record({
  'id' : ConversationId,
  'title' : IDL.Text,
  'sessionKey' : SessionKey,
  'messages' : IDL.Vec(Message),
  'createdAt' : Timestamp,
});
export const ConversationSummary = IDL.Record({
  'id' : ConversationId,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'messageCount' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'createConversation' : IDL.Func([SessionKey, IDL.Text], [ConversationId], []),
  'deleteConversation' : IDL.Func([SessionKey, ConversationId], [IDL.Bool], []),
  'getConversation' : IDL.Func(
      [SessionKey, ConversationId],
      [IDL.Opt(ConversationPublic)],
      ['query'],
    ),
  'listConversations' : IDL.Func(
      [SessionKey],
      [IDL.Vec(ConversationSummary)],
      ['query'],
    ),
  'renameConversation' : IDL.Func(
      [SessionKey, ConversationId, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'sendMessage' : IDL.Func(
      [SessionKey, ConversationId, IDL.Text],
      [IDL.Text],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionKey = IDL.Text;
  const ConversationId = IDL.Nat;
  const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const Timestamp = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : Role,
    'timestamp' : Timestamp,
  });
  const ConversationPublic = IDL.Record({
    'id' : ConversationId,
    'title' : IDL.Text,
    'sessionKey' : SessionKey,
    'messages' : IDL.Vec(Message),
    'createdAt' : Timestamp,
  });
  const ConversationSummary = IDL.Record({
    'id' : ConversationId,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'messageCount' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'createConversation' : IDL.Func(
        [SessionKey, IDL.Text],
        [ConversationId],
        [],
      ),
    'deleteConversation' : IDL.Func(
        [SessionKey, ConversationId],
        [IDL.Bool],
        [],
      ),
    'getConversation' : IDL.Func(
        [SessionKey, ConversationId],
        [IDL.Opt(ConversationPublic)],
        ['query'],
      ),
    'listConversations' : IDL.Func(
        [SessionKey],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'renameConversation' : IDL.Func(
        [SessionKey, ConversationId, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'sendMessage' : IDL.Func(
        [SessionKey, ConversationId, IDL.Text],
        [IDL.Text],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };