/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ConversationId = bigint;
export interface ConversationPublic {
  'id' : ConversationId,
  'title' : string,
  'sessionKey' : SessionKey,
  'messages' : Array<Message>,
  'createdAt' : Timestamp,
}
export interface ConversationSummary {
  'id' : ConversationId,
  'title' : string,
  'createdAt' : Timestamp,
  'messageCount' : bigint,
}
export interface Message {
  'content' : string,
  'role' : Role,
  'timestamp' : Timestamp,
}
export type Role = { 'user' : null } |
  { 'assistant' : null };
export type SessionKey = string;
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'createConversation' : ActorMethod<[SessionKey, string], ConversationId>,
  'deleteConversation' : ActorMethod<[SessionKey, ConversationId], boolean>,
  'getConversation' : ActorMethod<
    [SessionKey, ConversationId],
    [] | [ConversationPublic]
  >,
  'listConversations' : ActorMethod<[SessionKey], Array<ConversationSummary>>,
  'renameConversation' : ActorMethod<
    [SessionKey, ConversationId, string],
    boolean
  >,
  'sendMessage' : ActorMethod<[SessionKey, ConversationId, string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];